# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1105914d1308d3d9c3ede51dc1c8a88b"
name = "Sneakerzone Discounts"
application_url = "https://arline-superheroic-dooly.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory-levels"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products-update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://arline-superheroic-dooly.ngrok-free.dev/auth/callback"]
